[project]
name = "codecrafters-claude-code"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "openai>=2.17.0",
    "prompt-toolkit>=3.0.52",
]

[project.scripts]
bash-ai = "app.main:main"
